---
- name: "Install mandatory tools | base soft"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "software-properties-common"
    - "unattended-upgrades"
    - "mailutils"
    - "bsd-mailx"