---
- name: "pi-secure-user | Add alternate users"
  user:
    name: "{{ item.username | mandatory }}"
    comment: "{{ item.fullname | default(omit) }}"
    shell: "{{ item.shell | default(pi_secure_user_default_shell) }}"
    password: "{{ item.password | mandatory }}"
    group: "pi"
    state: "present"
    update_password: on_create
    groups: "{{ pi_secure_user_default_admin_groups }}"
    append: yes
  with_items: "{{ pi_secure_user_alternate_users }}"
- name: "pi-secure-user | Change default password for user 'pi'"
  user:
    name: "pi"
    password: "{{ pi_secure_user_custom_pi_password }}"
    state: "present"
    update_password: always
