---
- name: "pi-secure-user | Add 010_pi-passwd sudoers configuration files"
  become: yes
  copy:
    dest: "/etc/sudoers.d/010_pi-passwd"
    group: "root"
    owner: "root"
    mode: "0440"
    content: |
      pi ALL=(ALL) PASSWD: ALL
    validate: 'visudo -cf %s'

- name: "pi-secure-user | Disable 010_pi-nopasswd sudoers configuration files"
  become: yes
  lineinfile:
    path: "/etc/sudoers.d/010_pi-nopasswd"
    regexp: 'pi ALL=(ALL) NOPASSWD: ALL'
    line: '#pi ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    
- name: "pi-secure-user | Add admin users as sudoers"
  become: yes
  copy:
    dest: "/etc/sudoers.d/010_{{ item.username }}-nopasswd"
    group: "root"
    owner: "root"
    mode: "0440"
    content: |
      {{ item.username}} ALL=(ALL) NOPASSWD: ALL
    validate: 'visudo -cf %s'
  with_items: "{{ pi_secure_user_alternate_users }}"
